/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:240: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
[Epoch 001] Contrastive Loss: 5.9243
[Epoch 002] Contrastive Loss: 5.6172
Traceback (most recent call last):
  File "/users/c/carvalhj/projects/eurosat_preprocessing/exploratory_notebooks/simclr/main.py", line 5, in <module>
    train_simclr(CONFIG)
  File "/users/c/carvalhj/projects/eurosat_preprocessing/exploratory_notebooks/simclr/train.py", line 78, in train_simclr
    acc = run_logistic_probe(
  File "/users/c/carvalhj/projects/eurosat_preprocessing/exploratory_notebooks/simclr/probes/logistic.py", line 96, in run_logistic_probe
    probe.fit(probe_train_loader)
  File "/users/c/carvalhj/projects/eurosat_preprocessing/exploratory_notebooks/simclr/probes/logistic.py", line 50, in fit
    self.clf.fit(X, y)
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1239, in fit
    X, y = validate_data(
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 2971, in validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1385, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1406, in _check_y
    y = column_or_1d(y, warn=True)
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1454, in column_or_1d
    y = check_array(
  File "/users/c/carvalhj/miniconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1099, in check_array
    raise ValueError(
ValueError: Found array with dim 4, while dim <= 2 is required.
